# Generated by Django 4.2.5 on 2023-11-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('idsp', models.AutoField(primary_key=True, serialize=False)),
                ('anhsp', models.CharField(max_length=255)),
                ('tensp', models.CharField(max_length=100)),
                ('tenkhac', models.CharField(blank=True, max_length=100, null=True)),
                ('tenKhoahoc', models.CharField(blank=True, max_length=100, null=True)),
                ('congdung', models.CharField(blank=True, max_length=255, null=True)),
                ('mota', models.TextField()),
                ('baithuoc', models.CharField(blank=True, max_length=255, null=True)),
                ('giaban', models.BigIntegerField()),
                ('SLton', models.IntegerField()),
            ],
            options={
                'db_table': 'sanpham',
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('avt', models.CharField(max_length=255)),
                ('tendn', models.CharField(max_length=50)),
                ('hoten', models.CharField(max_length=100)),
                ('gioitinh', models.CharField(max_length=10)),
                ('sdt', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('diachi', models.CharField(max_length=255)),
                ('matkhau', models.CharField(max_length=255)),
                ('quyen', models.CharField(default='user', max_length=20)),
            ],
            options={
                'db_table': 'taikhoan',
            },
        ),
    ]
