# Generated by Django 4.2.5 on 2023-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='anhsp',
            field=models.TextField(max_length=255),
        ),
    ]
