# Generated by Django 4.2.5 on 2023-11-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0003_alter_sanpham_anhsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='baithuoc',
            field=models.TextField(),
        ),
    ]
