# Generated by Django 4.2.5 on 2023-11-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0004_alter_sanpham_baithuoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanpham',
            old_name='tenKhoahoc',
            new_name='tenkhoahoc',
        ),
    ]
