# Generated by Django 4.2.5 on 2023-11-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0005_rename_tenkhoahoc_sanpham_tenkhoahoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='luottruycap',
            field=models.IntegerField(default=0),
        ),
    ]
