# Generated by Django 4.2.5 on 2023-11-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0006_sanpham_luottruycap'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenhCam',
            fields=[
                ('idbenh', models.AutoField(primary_key=True, serialize=False)),
                ('tenbenh', models.CharField(max_length=255)),
                ('anhbenh', models.CharField(max_length=255)),
                ('noidung', models.TextField()),
            ],
            options={
                'db_table': 'benhcam',
            },
        ),
    ]
