# Generated by Django 4.2.5 on 2023-11-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0007_benhcam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhcam',
            name='anhbenh',
            field=models.TextField(),
        ),
    ]
