# Generated by Django 4.2.5 on 2023-11-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0008_alter_benhcam_anhbenh'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('idtt', models.AutoField(primary_key=True, serialize=False)),
                ('tieude', models.CharField(max_length=255)),
                ('anhtt', models.CharField(max_length=255)),
                ('mota', models.TextField()),
                ('noidung', models.TextField()),
                ('ngaydang', models.DateField(auto_now_add=True)),
                ('luottruycap', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tintuc',
            },
        ),
    ]
