# Generated by Django 4.2.5 on 2023-11-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0009_tintuc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('idhd', models.AutoField(primary_key=True, serialize=False)),
                ('ngaylap', models.DateTimeField(auto_now_add=True)),
                ('tongtien', models.BigIntegerField()),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbal.taikhoan')),
            ],
            options={
                'db_table': 'hoadon',
            },
        ),
        migrations.CreateModel(
            name='ChiTietHD',
            fields=[
                ('idcthd', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField()),
                ('idhd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbal.hoadon')),
                ('idsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbal.sanpham')),
            ],
            options={
                'db_table': 'chitiethd',
            },
        ),
    ]
