# Generated by Django 4.2.5 on 2023-11-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0010_hoadon_chitiethd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='tongtien',
            field=models.BigIntegerField(default=0),
        ),
    ]
