# Generated by Django 4.2.5 on 2023-11-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0011_alter_hoadon_tongtien'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='dathanhtoan',
            field=models.BooleanField(default=False),
        ),
    ]
