# Generated by Django 4.2.5 on 2023-11-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0012_hoadon_dathanhtoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='anhtt',
            field=models.TextField(),
        ),
    ]
