# Generated by Django 4.2.5 on 2023-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0013_alter_tintuc_anhtt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='avt',
            field=models.CharField(default='https://res-console.cloudinary.com/dscipc01t/thumbnails/v1/image/upload/v1701511852/QWNjb3VudC91c2VyX2U4bHBnZg==/grid_landscape', max_length=255),
        ),
    ]
