# Generated by Django 4.2.5 on 2023-12-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0014_alter_taikhoan_avt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoadon',
            old_name='dathanhtoan',
            new_name='dadathang',
        ),
    ]
