# Generated by Django 4.2.5 on 2023-12-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0016_alter_taikhoan_avt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('idpn', models.AutoField(primary_key=True, serialize=False)),
                ('ngaynhap', models.DateTimeField(auto_now_add=True)),
                ('tongtien', models.BigIntegerField()),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbal.taikhoan')),
            ],
            options={
                'db_table': 'phieunhap',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPN',
            fields=[
                ('idctpn', models.AutoField(primary_key=True, serialize=False)),
                ('soluongnhap', models.IntegerField()),
                ('dongianhap', models.BigIntegerField()),
                ('idpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbal.phieunhap')),
                ('idsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbal.sanpham')),
            ],
            options={
                'db_table': 'chitietpn',
            },
        ),
    ]
