# Generated by Django 4.2.5 on 2023-12-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0017_phieunhap_chitietpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='SLton',
            field=models.IntegerField(default=0),
        ),
    ]
